# Generated by Django 4.1.2 on 2022-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('upload_image', models.ImageField(upload_to='reseller/')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
